semver: 2.11.4
header:
  name: SprayBot
  bitmap: ""
  labels: ""
  modelId:
    0:
      val: 0
noGlobalFunctions: 0
thrTrim: 0
trimInc: 0
displayTrims: 0
ignoreSensorIds: 0
showInstanceIds: 0
disableThrottleWarning: 0
enableCustomThrottleWarning: 0
customThrottleWarningPosition: 0
beepANACenter: 0
extendedLimits: 1
extendedTrims: 0
throttleReversed: 0
checklistInteractive: 0
flightModeData:
  0:
    trim:
      0:
        value: -10
        mode: 0
      1:
        value: -26
        mode: 0
      3:
        value: 20
        mode: 0
    name: ""
    fadeIn: 0
    fadeOut: 0
mixData:
  - destCh: 0
    srcRaw: I0
    weight: 100
    swtch: NONE
    curve:
      type: 0
      value: 0
    delayPrec: 0
    delayUp: 0
    delayDown: 0
    speedPrec: 0
    speedUp: 0
    speedDown: 0
    carryTrim: 0
    mltpx: ADD
    mixWarn: 0
    flightModes: 000000000
    offset: 0
    name: ""
  - destCh: 1
    srcRaw: I2
    weight: 100
    swtch: NONE
    curve:
      type: 0
      value: 0
    delayPrec: 0
    delayUp: 0
    delayDown: 0
    speedPrec: 0
    speedUp: 0
    speedDown: 0
    carryTrim: 0
    mltpx: ADD
    mixWarn: 0
    flightModes: 000000000
    offset: 0
    name: ""
  - destCh: 2
    srcRaw: I1
    weight: 100
    swtch: NONE
    curve:
      type: 0
      value: 0
    delayPrec: 0
    delayUp: 0
    delayDown: 0
    speedPrec: 0
    speedUp: 0
    speedDown: 0
    carryTrim: 0
    mltpx: ADD
    mixWarn: 0
    flightModes: 000000000
    offset: 0
    name: ""
  - destCh: 3
    srcRaw: I3
    weight: 100
    swtch: NONE
    curve:
      type: 0
      value: 0
    delayPrec: 0
    delayUp: 0
    delayDown: 0
    speedPrec: 0
    speedUp: 0
    speedDown: 0
    carryTrim: 0
    mltpx: ADD
    mixWarn: 0
    flightModes: 000000000
    offset: 0
    name: ""
  - destCh: 4
    srcRaw: SA
    weight: 100
    swtch: NONE
    curve:
      type: 0
      value: 0
    delayPrec: 0
    delayUp: 0
    delayDown: 0
    speedPrec: 0
    speedUp: 0
    speedDown: 0
    carryTrim: 0
    mltpx: ADD
    mixWarn: 0
    flightModes: 000000000
    offset: 0
    name: ""
  - destCh: 5
    srcRaw: SD
    weight: 100
    swtch: NONE
    curve:
      type: 0
      value: 0
    delayPrec: 0
    delayUp: 0
    delayDown: 0
    speedPrec: 0
    speedUp: 0
    speedDown: 0
    carryTrim: 0
    mltpx: ADD
    mixWarn: 0
    flightModes: 000000000
    offset: 0
    name: ""
  - destCh: 6
    srcRaw: SB
    weight: 100
    swtch: NONE
    curve:
      type: 0
      value: 0
    delayPrec: 0
    delayUp: 0
    delayDown: 0
    speedPrec: 0
    speedUp: 0
    speedDown: 0
    carryTrim: 0
    mltpx: ADD
    mixWarn: 0
    flightModes: 000000000
    offset: 0
    name: ""
  - destCh: 7
    srcRaw: SC
    weight: 100
    swtch: NONE
    curve:
      type: 0
      value: 0
    delayPrec: 0
    delayUp: 0
    delayDown: 0
    speedPrec: 0
    speedUp: 0
    speedDown: 0
    carryTrim: 0
    mltpx: ADD
    mixWarn: 0
    flightModes: 000000000
    offset: 0
    name: ""
  - destCh: 8
    srcRaw: SE
    weight: 100
    swtch: NONE
    curve:
      type: 3
      value: 1
    delayPrec: 0
    delayUp: 0
    delayDown: 0
    speedPrec: 0
    speedUp: 0
    speedDown: 0
    carryTrim: 0
    mltpx: ADD
    mixWarn: 0
    flightModes: 000000000
    offset: 0
    name: ""
  - destCh: 11
    srcRaw: SE
    weight: 100
    swtch: NONE
    curve:
      type: 3
      value: 2
    delayPrec: 0
    delayUp: 0
    delayDown: 0
    speedPrec: 0
    speedUp: 0
    speedDown: 0
    carryTrim: 0
    mltpx: ADD
    mixWarn: 0
    flightModes: 000000000
    offset: 0
    name: ""
limitData:
  0:
    min: 0
    max: 0
    revert: 0
    offset: 0
    ppmCenter: 0
    symetrical: 0
    name: ""
    curve: 32
  1:
    min: 0
    max: 0
    revert: 0
    offset: 0
    ppmCenter: 0
    symetrical: 0
    name: ""
    curve: 32
  3:
    min: 0
    max: 0
    revert: 0
    offset: 0
    ppmCenter: 0
    symetrical: 0
    name: ""
    curve: 32
expoData:
  - srcRaw: Rud
    scale: 0
    mode: 3
    chn: 0
    swtch: NONE
    flightModes: 000000000
    weight: 100
    offset: 0
    curve:
      type: 1
      value: 0
    trimSource: 0
    name: ""
  - srcRaw: Ele
    scale: 0
    mode: 3
    chn: 1
    swtch: NONE
    flightModes: 000000000
    weight: 100
    offset: 0
    curve:
      type: 1
      value: 0
    trimSource: 0
    name: ""
  - srcRaw: Thr
    scale: 0
    mode: 3
    chn: 2
    swtch: NONE
    flightModes: 000000000
    weight: 100
    offset: 0
    curve:
      type: 1
      value: 0
    trimSource: 0
    name: ""
  - srcRaw: Ail
    scale: 0
    mode: 3
    chn: 3
    swtch: NONE
    flightModes: 000000000
    weight: 100
    offset: 0
    curve:
      type: 1
      value: 0
    trimSource: 0
    name: ""
inputNames:
  0:
    val: Rud
  1:
    val: Ele
  2:
    val: Thr
  3:
    val: Ail
curves:
  0:
    type: 1
    smooth: 0
    points: -3
    name: ""
  1:
    type: 0
    smooth: 0
    points: -3
    name: ""
  31:
    type: 1
    smooth: 0
    points: -1
    name: CNT
points:
  0:
    val: -100
  1:
    val: 29
  2:
    val: 29
  3:
    val: -100
  149:
    val: -100
  150:
    val: 0
  151:
    val: 0
  152:
    val: 100
  153:
    val: -1
  154:
    val: 1
swashR:
  type: TYPE_NONE
  value: 0
  collectiveSource: NONE
  aileronSource: NONE
  elevatorSource: NONE
  collectiveWeight: 0
  aileronWeight: 0
  elevatorWeight: 0
thrTraceSrc: Thr
switchWarning:
  SA:
    pos: up
  SB:
    pos: up
  SC:
    pos: up
  SD:
    pos: up
thrTrimSw: 0
potsWarnMode: WARN_OFF
potsWarnEnabled: 0
jitterFilter: GLOBAL
displayChecklist: 0
telemetryProtocol: 0
screens:
  0:
    type: VALUES
    u:
      lines:
        0: ~
        1:
          sources:
            0:
              val: TX_VOLTAGE
            1:
              val: TX_TIME
        2: ~
        3: ~
varioData:
  source: none
  centerSilent: 0
  centerMax: 0
  centerMin: 0
  min: 0
  max: 0
rssiSource: none
rfAlarms:
  warning: 45
  critical: 42
disableTelemetryWarning: 0
moduleData:
  0:
    type: TYPE_CROSSFIRE
    channelsStart: 0
    channelsCount: 16
    failsafeMode: NOT_SET
    mod:
      crsf:
        telemetryBaudrate: 0
        crsfArmingMode: 0
        crsfArmingTrigger: NONE
trainerData:
  mode: OFF
  channelsStart: 0
  channelsCount: -8
  frameLength: 0
  delay: 0
  pulsePol: 0
telemetrySensors:
  0:
    type: TYPE_CUSTOM
    id1:
      id: 20
    subId: 0
    id2:
      instance: 0
    label: 1RSS
    unit: 17
    prec: 0
    autoOffset: 0
    filter: 0
    logs: 1
    persistent: 0
    onlyPositive: 0
    cfg:
      custom:
        ratio: 0
        offset: 0
  1:
    type: TYPE_CUSTOM
    id1:
      id: 20
    subId: 0
    id2:
      instance: 1
    label: 2RSS
    unit: 17
    prec: 0
    autoOffset: 0
    filter: 0
    logs: 1
    persistent: 0
    onlyPositive: 0
    cfg:
      custom:
        ratio: 0
        offset: 0
  2:
    type: TYPE_CUSTOM
    id1:
      id: 20
    subId: 0
    id2:
      instance: 2
    label: RQly
    unit: 13
    prec: 0
    autoOffset: 0
    filter: 0
    logs: 1
    persistent: 0
    onlyPositive: 0
    cfg:
      custom:
        ratio: 0
        offset: 0
  3:
    type: TYPE_CUSTOM
    id1:
      id: 20
    subId: 0
    id2:
      instance: 3
    label: RSNR
    unit: 17
    prec: 0
    autoOffset: 0
    filter: 0
    logs: 1
    persistent: 0
    onlyPositive: 0
    cfg:
      custom:
        ratio: 0
        offset: 0
  4:
    type: TYPE_CUSTOM
    id1:
      id: 20
    subId: 0
    id2:
      instance: 4
    label: ANT
    unit: 0
    prec: 0
    autoOffset: 0
    filter: 0
    logs: 1
    persistent: 0
    onlyPositive: 0
    cfg:
      custom:
        ratio: 0
        offset: 0
  5:
    type: TYPE_CUSTOM
    id1:
      id: 20
    subId: 0
    id2:
      instance: 5
    label: RFMD
    unit: 0
    prec: 0
    autoOffset: 0
    filter: 0
    logs: 1
    persistent: 0
    onlyPositive: 0
    cfg:
      custom:
        ratio: 0
        offset: 0
  6:
    type: TYPE_CUSTOM
    id1:
      id: 20
    subId: 0
    id2:
      instance: 6
    label: TPWR
    unit: 16
    prec: 0
    autoOffset: 0
    filter: 0
    logs: 1
    persistent: 0
    onlyPositive: 0
    cfg:
      custom:
        ratio: 0
        offset: 0
  7:
    type: TYPE_CUSTOM
    id1:
      id: 20
    subId: 0
    id2:
      instance: 7
    label: TRSS
    unit: 17
    prec: 0
    autoOffset: 0
    filter: 0
    logs: 1
    persistent: 0
    onlyPositive: 0
    cfg:
      custom:
        ratio: 0
        offset: 0
  8:
    type: TYPE_CUSTOM
    id1:
      id: 20
    subId: 0
    id2:
      instance: 8
    label: TQly
    unit: 13
    prec: 0
    autoOffset: 0
    filter: 0
    logs: 1
    persistent: 0
    onlyPositive: 0
    cfg:
      custom:
        ratio: 0
        offset: 0
  9:
    type: TYPE_CUSTOM
    id1:
      id: 20
    subId: 0
    id2:
      instance: 9
    label: TSNR
    unit: 17
    prec: 0
    autoOffset: 0
    filter: 0
    logs: 1
    persistent: 0
    onlyPositive: 0
    cfg:
      custom:
        ratio: 0
        offset: 0
  10:
    type: TYPE_CUSTOM
    id1:
      id: 8
    subId: 0
    id2:
      instance: 0
    label: RxBt
    unit: 1
    prec: 1
    autoOffset: 0
    filter: 0
    logs: 1
    persistent: 0
    onlyPositive: 0
    cfg:
      custom:
        ratio: 0
        offset: 2
  11:
    type: TYPE_CUSTOM
    id1:
      id: 8
    subId: 0
    id2:
      instance: 1
    label: Curr
    unit: 2
    prec: 1
    autoOffset: 0
    filter: 0
    logs: 1
    persistent: 0
    onlyPositive: 0
    cfg:
      custom:
        ratio: 0
        offset: 0
  12:
    type: TYPE_CUSTOM
    id1:
      id: 8
    subId: 0
    id2:
      instance: 2
    label: Capa
    unit: 14
    prec: 0
    autoOffset: 0
    filter: 0
    logs: 1
    persistent: 0
    onlyPositive: 0
    cfg:
      custom:
        ratio: 0
        offset: 0
  13:
    type: TYPE_CUSTOM
    id1:
      id: 8
    subId: 0
    id2:
      instance: 3
    label: Bat
    unit: 13
    prec: 0
    autoOffset: 0
    filter: 0
    logs: 1
    persistent: 0
    onlyPositive: 0
    cfg:
      custom:
        ratio: 0
        offset: 0
modelRegistrationID: "*\x15*\x15!\x03%\x07"
hatsMode: GLOBAL
usbJoystickExtMode: 0
usbJoystickIfMode: JOYSTICK
usbJoystickCircularCut: 0
radioGFDisabled: GLOBAL
radioTrainerDisabled: GLOBAL
modelHeliDisabled: GLOBAL
modelFMDisabled: GLOBAL
modelCurvesDisabled: GLOBAL
modelGVDisabled: GLOBAL
modelLSDisabled: GLOBAL
modelSFDisabled: GLOBAL
modelCustomScriptsDisabled: GLOBAL
modelTelemetryDisabled: GLOBAL